# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: G:/traffic-analyzer/xdc/extract_traffic_attributes.xdc

# IP: ip/dcfifo_10_bits_16_deep/dcfifo_10_bits_16_deep.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dcfifo_10_bits_16_deep || ORIG_REF_NAME==dcfifo_10_bits_16_deep} -quiet] -quiet

# IP: ip/phase90_shift/phase90_shift.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==phase90_shift || ORIG_REF_NAME==phase90_shift} -quiet] -quiet
